name: Deploy Without VPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: SSH_HOST
    steps:
      - name: Debug SSH_HOST
        run: echo "SSH_HOST=(${SSH_HOST})"
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            APP_NAME="pos-siigo"
            BASE_PATH="/home/deploy/github"
            APP_PATH="$BASE_PATH/$APP_NAME"
            REPO_URL="git@github.com:michael2002Sof/POSinnovate-Siigo.git"

            echo "=========== 📁 Verificando carpeta ==========="
            if [ ! -d "$APP_PATH" ]; then
              echo "⚠️ Carpeta no existe → creando..."
              mkdir -p $APP_PATH
              echo "⬇️ Clonando repositorio..."
              git clone $REPO_URL $APP_PATH
            else
              echo "📂 Carpeta existe"
              cd $APP_PATH
              if [ ! -d ".git" ]; then
                echo "⚠️ No hay .git → clonando repo..."
                git clone $REPO_URL $APP_PATH
              else
                echo "🔄 Repo detectado → ejecutando git pull..."
                git pull origin main
              fi
            fi

            cd $APP_PATH

            echo "=========== 📦 Instalando dependencias ==========="
            npm install

            echo "=========== 🔍 Verificando PM2 ==========="
            pm2 describe $APP_NAME > /dev/null 2>&1

            if [ $? -eq 0 ]; then
              echo "♻️ Proceso PM2 encontrado → reiniciando..."
              pm2 restart $APP_NAME
            else
              echo "🚀 Proceso no existe → iniciando con ecosystem.config.cjs..."
              pm2 start ecosystem.config.cjs --name $APP_NAME
            fi

            echo "=========== 💾 Guardando estado PM2 ==========="
            pm2 save

            echo "=========== ✅ DEPLOY FINALIZADO ==========="
