name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_ed25519 deploy@${{ secrets.SERVER_HOST }} << 'EOF'

            PROJECT_DIR="/home/deploy/github/POSinnovate-Siigo"

            echo "📌 Verificando existencia del proyecto..."
            if [ -d "$PROJECT_DIR/.git" ]; then
              echo "✔ El proyecto ya existe, haciendo git pull"
              cd "$PROJECT_DIR"
              git pull
            else
              echo "⬇ El proyecto NO existe, clonando repositorio..."
              mkdir -p /home/deploy/github
              cd /home/deploy/github
              git clone git@github.com:michael2002Sof/POSinnovate-Siigo.git
              cd POSinnovate-Siigo
            fi

            echo "📦 Instalando dependencias..."
            npm install --omit=dev

            echo "⚡ Construyendo proyecto..."
            npm run build

            echo "🚀 Reiniciando servicio con PM2..."
            pm2 restart pos-siigo || pm2 start dist/main.js --name pos-siigo

          EOF
