name: Deploy Without VPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: SSH_HOST

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            APP_NAME="pos-siigo"
            APP_PATH="/home/deploy/github/pos-siigo"
            REPO_URL="https://github.com/michael2002Sof/POSinnovate-Siigo.git"

            echo "📁 Verificando carpeta del proyecto..."
            if [ ! -d "$APP_PATH" ]; then
              echo "⚠️ La carpeta no existe, creando..."
              mkdir -p $APP_PATH
              chown -R deploy:deploy /home/deploy/github
            fi

            echo "📁 Entrando al proyecto"
            cd $APP_PATH

            echo "⬇️ Clonando/actualizando repositorio..."
            if [ ! -d ".git" ]; then
              git clone $REPO_URL $APP_PATH
            else
              git pull origin main
            fi

            echo "📦 Instalando dependencias..."
            npm install --production

            echo "🔍 Comprobando si PM2 ya tiene el proceso..."
            pm2 describe $APP_NAME > /dev/null 2>&1

            if [ $? -eq 0 ]; then
              echo "♻️ Proceso existe → Reiniciando..."
              pm2 restart $APP_NAME
            else
              echo "🚀 Proceso NO existe → Creando servicio PM2..."
              pm2 start index.js --name $APP_NAME
            fi

            echo "💾 Guardando procesos PM2"
            pm2 save
